# site name
prefixName: 不安きのこ
siteName: Site
# favicon and site master avatar
favicon: https://cdn.jsdelivr.net/gh/Fuann-Kinoko/cdn@0.1/favicon/bitbug_favicon.ico
avatar: https://i.loli.net/2020/02/09/KxCtIyfFesrv4Zw.jpg
url: https://fuann-kinoko.github.io/
description: Vtuber废人/游戏废人
#cdn: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6
pjax: 1
# 1开启
mathjax: 0

notice: 博客维修中……
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    题解: {path: /categories/题解/, fa: fa-code }, 
    记录: {path: /categories/记录/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
 #   书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: https://bgm.tv/user/403965, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
 #   图集: {path: /tags/图集/, fa: fa-photo }
  } }
#  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
#  友人帐: { path: /links/, fa: fa-link faa-shake }
#  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
 #   主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
 #   Lab: {path: /lab/, fa: fa-cogs },
  } }
#  客户端: { path: /client/, fa: fa-android faa-vertical }
 # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
#    - https://cdn.jsdelivr.net/gh/Fuann-Kinoko/cdn@0.1/Covers/(6).webp
   - https://cdn.jsdelivr.net/gh/Fuann-Kinoko/cdn@0.1/Covers/(1).webp
   - https://cdn.jsdelivr.net/gh/Fuann-Kinoko/cdn@0.1/Covers/(2).webp
   - https://cdn.jsdelivr.net/gh/Fuann-Kinoko/cdn@0.1/Covers/(3).webp
   - https://cdn.jsdelivr.net/gh/Fuann-Kinoko/cdn@0.1/Covers/(4).webp
   - https://cdn.jsdelivr.net/gh/Fuann-Kinoko/cdn@0.1/Covers/(5).webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(1).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(2).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(3).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(4).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(5).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(6).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(7).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(8).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: https://space.bilibili.com/4415701, title: にじさんじ, desc: , img: https://cdn.jsdelivr.net/gh/Fuann-Kinoko/cdn@0.1/startdash/nijisanji.webp}
  - {url: https://space.bilibili.com/11564096, title: Bilibili, desc: , img: https://cdn.jsdelivr.net/gh/Fuann-Kinoko/cdn@0.1/startdash/bilibili2.jpg}
  - {url: http://www.dream-pro.info/~lavalse/LR2IR/search.cgi/, title: Lunatic Rave 2, desc: , img: https://cdn.jsdelivr.net/gh/Fuann-Kinoko/cdn@0.1/startdash/lr21.jpg}



# your site build time or founded date
siteBuildingTime: 10/03/2019

#social  url, img PC端配置
social:
  github: {url: http://github.com/honjun, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/github.png}
#  sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/wangyiyun.png}
  bangumi: {url: https://bgm.tv/user/403965, img: https://i.loli.net/2019/11/23/mk41cgeCGZo5hjM.png}
#  email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
 # wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/honjun, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate: false
#  enable: false
#  paypal: https://www.paypal.me/hojuncn
#  alipay: /img/custom/donate/AliPayQR.jpg
#  wechat: /img/custom/donate/WeChanQR.jpg
#  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2605607777
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

gitalk:
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: 'ec9b058fe1ac5ff50321'
    # 应用秘钥
    clientSecret: 'c15b5207147bf6307553ec6f3ed08147a941d30b'
    # issue仓库名
    repo: 'Fuann-Kinoko.github.io'
    # Github名
    owner: 'Fuann-Kinoko'
    # Github名
    admin: ['Fuann-Kinoko']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false
